MODULESPATH = ./modules

MODULESSRC = $(MODULESPATH)/bubbles/bubbles.c
MODULESSRC += $(MODULESPATH)/rtt_shell/rtt_shell.c
MODULESSRC += $(MODULESPATH)/buzzer/buzzer.c
MODULESSRC += $(MODULESPATH)/UMD/umd.c
MODULESSRC += $(MODULESPATH)/analog/analog.c
MODULESSRC += $(MODULESPATH)/usage/usage.c
MODULESSRC += $(MODULESPATH)/RTT/SEGGER_RTT.c
MODULESSRC += $(MODULESPATH)/RTT/RTTchannel.c
MODULESSRC += $(MODULESPATH)/RTT/RTTLog.c
MODULESSRC += $(MODULESPATH)/DS4/ds4.c
#MODULESSRC += $(MODULESPATH)/Log/log.c


MODULESINC = $(MODULESPATH)/bubbles
MODULESINC += $(MODULESPATH)/rtt_shell
MODULESINC += $(MODULESPATH)/buzzer
MODULESINC += $(MODULESPATH)/UMD
MODULESINC += $(MODULESPATH)/analog
MODULESINC += $(MODULESPATH)/usage
MODULESINC += $(MODULESPATH)/RTT
MODULESINC += $(MODULESPATH)/DS4
MODULESINC += $(MODULESPATH)/Log

include $(MODULESPATH)/ui/ui.mk