MODULESPATH = ./modules

MODULESSRC = $(MODULESPATH)/bubbles/bubbles.c
MODULESSRC += $(MODULESPATH)/usb_shell/usb_shell.c
MODULESSRC += $(MODULESPATH)/buzzer/buzzer.c
MODULESSRC += $(MODULESPATH)/UDC/udc.c
MODULESSRC += $(MODULESPATH)/UDC/udc_lld.c
MODULESSRC += $(MODULESPATH)/usage/usage.c


MODULESINC = $(MODULESPATH)/bubbles
MODULESINC += $(MODULESPATH)/usb_shell
MODULESINC += $(MODULESPATH)/buzzer
MODULESINC += $(MODULESPATH)/UDC
MODULESINC += $(MODULESPATH)/usage

include $(MODULESPATH)/ui/ui.mk