/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// Widget groups
#define GROUP_DEFAULT 0

// GListeners
extern GListener gl;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle ghContainer1;
extern GHandle ghProgressbar1;
extern GHandle ghContainer2;
extern GHandle ghProgressbar2;
extern GHandle ghContainer3;
extern GHandle ghContainer4;
extern GHandle ghLabelm0;
extern GHandle ghLabelm1;
extern GHandle ghLabelm2;
extern GHandle ghLabelm3;
extern GHandle ghLabelm4;
extern GHandle ghLabelm5;
extern GHandle ghLabel2;
extern GHandle ghLabelM2_Setpoint;
extern GHandle ghLabelM4_Setpoint;
extern GHandle ghLabelM0_Setpoint;
extern GHandle ghLabelM1_Setpoint;
extern GHandle ghLabelM3_Setpoint;
extern GHandle ghLabelM5_Setpoint;
extern GHandle ghLabelM6_Setpoint;
extern GHandle ghLabelM7_Setpoint;
extern GHandle ghLabelm7;
extern GHandle ghLabelm6;
extern GHandle ghLabele1;
extern GHandle ghLabele3;
extern GHandle ghLabelM0_Feedback;
extern GHandle ghLabelM1_Feedback;
extern GHandle ghLabelM2_Feedback;
extern GHandle ghLabelM3_Feedback;
extern GHandle ghLabelM4_Feedback;
extern GHandle ghLabelM5_Feedback;
extern GHandle ghLabelM6_Feedback;
extern GHandle ghLabelM7_Feedback;
extern GHandle ghLabelM0_Current;
extern GHandle ghLabelM1_Current;
extern GHandle ghLabelM2_Current;
extern GHandle ghLabelM3_Current;
extern GHandle ghLabelM4_Current;
extern GHandle ghLabelM5_Current;
extern GHandle ghLabelM6_Current;
extern GHandle ghLabelM7_Current;
extern GHandle ghLabele2;
extern GHandle ghLabele4;
extern GHandle ghLabelE1_count;
extern GHandle ghLabelE2_count;
extern GHandle ghLabelE3_count;
extern GHandle ghLabelE4_count;
extern GHandle ghConsole;
extern GHandle ghButtonStop;
extern GHandle ghButton1;
extern GHandle ghButton2;
extern GHandle ghButton3;
extern GHandle ghCheckboxMotor;
extern GHandle ghCheckboxEncoder;
extern GHandle ghLabelTimer;
extern GHandle ghButtonBack;
extern GHandle ghLabel35;
extern GHandle ghCheckboxDS4;
extern GHandle ghLabelCPU;
extern GHandle ghLabelCPU_VAL;
extern GHandle ghLabelMotorVolt;
extern GHandle ghLabelMotorVolt_VAL;
extern GHandle ghLabelMBVolt;
extern GHandle ghLabelMBVolt_VAL;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

